# Author: Michael Sevilla
# Start Ceph node with LTTnG

- name: move some startup scripts over there
  copy: src=/infra/roles/ceph-babeltrace/files/ dest={{ code_dir }}/

- name: make scripts executable
  command: chmod -R 750 {{ code_dir }}/scripts/

- name: start babeltrace container
  changed_when: False
  docker:
    image: michaelsevilla/babeltrace
    name: ceph-babetrace
    net: host
    volumes: 
      - "{{ code_dir }}/scripts:/scripts"
      - "{{ trace_dir }}/lttng:/lttng"
    state: restarted
    command: /scripts/latency.py -o /lttng/latencies.out -d /lttng/ust/uid/0/64-bit/

- name: print out the results in {{ trace_dir }}/lttng/latencies.out
  changed_when: False
  command: cat {{ trace_dir }}/lttng/latencies.out
  register: result
- debug: var=result.stdout_lines
