---
- name: figure out which configs the user has defined
  connection: local
  command: ls {{ dir.stdout }}/group_vars/swift_conf
  register: confs
  ignore_errors: True

- name: copy the user-defined configs to the remote note
  copy: src={{ dir.stdout }}/group_vars/swift_conf/{{ item }} dest=/etc/swift/{{ item }}
  with_items: confs.stdout_lines
  when: confs is defined

- name: set config and keys paths
  set_fact:
    swift_configs:
      - /etc/swift/account-server.template
      - /etc/swift/container-server.template
      - /etc/swift/object-expirer.conf
      - /etc/swift/proxy-server.template
      - /etc/swift/container-reconciler.conf
      - /etc/swift/container-sync-realms.conf
      - /etc/swift/object-server.template
      - /etc/swift/swift.conf
      - /etc/swift/remakerings
      - /etc/swift/object.ring.gz
      - /etc/swift/object-1.ring.gz
      - /etc/swift/object-2.ring.gz
      - /etc/swift/account.ring.gz
      - /etc/swift/container.ring.gz

- name: push swift files to the ansible server
  fetch:
    src: "{{ item }}"
    dest: "{{ fetch_directory }}/docker_swift_files/{{ item }}"
    flat: yes
  with_items: swift_configs
