---
- name: run the swift proxy docker image
  shell: >
         docker run -it -d \
         --name "{{ ansible_hostname }}-port{{ item }}-proxy" \
         --net host \
         --privileged \
         -e "IP={{ ansible_host }}" \
         -e "PORT={{ item }}" \
         -e "SWIFT_DAEMON=PROXY" \
         -v "/tmp/etc/swift/proxy{{ item }}/etc/swift:/etc/swift" \
         "{{ swift_docker_username }}/{{ swift_docker_imagename }}"
  with_items: swift_proxy_docker_ports
