---
- name: run the hadoop nodemanager docker image
  shell: >
    docker run -d \
      --name "hadoop-nodemanager" \
      --net "host" \
      -e "HADOOP_DAEMON=NODEMANAGER" \
      -e "HADOOP_CLASSPATH=/usr/local/hadoop/share/hadoop/tools/lib/*" \
      -e "YARN_CLASSPATH=/usr/local/hadoop/share/hadoop/tools/lib/*" \
      -v "/etc/hadoop:/etc/hadoop" \
      "{{ hadoop_docker_username }}/{{ hadoop_docker_imagename }}"
