---
- name: run the swift account daemon
  shell: >
         docker run -it -d \
           --name "{{ ansible_hostname }}-port{{ item }}-account" \
           --net host \
           --privileged \
           -e "IP={{ ansible_host }}" \
           -e "PORT={{ item }}" \
           -e "SWIFT_DAEMON=ACCOUNT" \
           -v "/tmp/etc/swift/account{{ item }}/etc/swift:/etc/swift" \
           "{{ swift_docker_username }}/{{ swift_docker_imagename }}" 
  with_items: swift_account_docker_ports
