---
- name: run the swift account daemon
  docker:
    image: "{{ swift_docker_username }}/{{ swift_docker_imagename }}"
    name: "{{ ansible_hostname }}-port{{ item }}-account"
    net: "host"
    state: "running"
    env: "IP={{ ansible_host }},PORT={{ item }},SWIFT_DAEMON=ACCOUNT,{{ swift_account_extra_envs }}"
    volumes: "/tmp/etc/swift/account{{ item }}/etc/swift:/etc/swift"
    detach: true
    tty: true
    privileged: true
  with_items: swift_account_docker_ports
