# Author: Michael Sevilla
# Cleanup containers on all nodes

- name: pull dependencies for running the emaster
  ignore_errors: True
  no_log: True
  docker: 
    image: michaelsevilla/emaster
    state: present

- name: start emaster container to clean stuff up
  docker:
    image: michaelsevilla/emaster
    name: "cleaner"
    state: restarted
    detach: yes
    tty: yes
    net: host
    privileged: yes
    volumes: 
      - "/tmp:/tmp"

- name: delete data
  shell: docker exec cleaner rm -rf /tmp/etc/ /tmp/ceph_data/ /usr/local/share/ceph/rados-classes/
  ignore_errors: True
  no_log: True

- name: stop containers (and their services) --> {{ containers }}
  shell: docker stop {{ item }}
  ignore_errors: True
  no_log: True
  with_items: "{{ containers }}"

- name: remove containers --> {{ containers }}
  shell: docker rm {{ item }}
  ignore_errors: True
  no_log: True
  with_items: "{{ containers }}"
