# Author: Michael Sevilla
# Cleanup containers on all nodes

- name: check if any other jobs are running
  shell: docker ps | grep -v emaster | grep -v CONTAINER
  register: result
  ignore_errors: True

- name: stop all containers, effectively stop  all services
  shell: docker ps -a | grep -v "emaster\|CONTAINER" | awk '{print $1}' | xargs docker stop
  ignore_errors: True
  when: result.rc == 0

- name: remove all containers, effectively killing all services
  shell: docker ps -a | grep -v "emaster\|CONTAINER" | awk '{print $1}' | xargs docker rm
  ignore_errors: True
  when: result.rc == 0
