# Author: Michael Sevilla
# Build Ceph in a container

- name: build ceph
  changed_when: False
  docker:
    image: ivotron/cephdev-build
    name: cephdev-build
    env:
      BUILD_THREADS: "{{ BUILD_THREADS }}"
      CEPH_PKGS: "{{ CEPH_PKGS }}"
      GIT_URL: "{{ GIT_URL }}"
      SHA1_OR_REF: "{{ SHA1_OR_REF }}"
    volumes:
      - '{{ code_dir }}/ceph:/ceph'

- name: wait for compile... (to see progress, ssh to node and run [docker logs cephdev-build])
  shell: >
    docker wait cephdev-build
  register: result

- name: fail if docker build fails
  fail: msg="Ceph build failed; check your environment variables above"
  # stdout returns strings, not an int
  when: result.stdout.find("0") == -1

