# Author: Michael Sevilla
# The code is already cloned so we just need to pacakge it up

- name: mount CephFS
  changed_when: False
  docker:
    image: ivotron/cephdev
    name: cephdev-fuse
    detach: yes
    tty: yes
    env:
      SSHD_PORT: 2222
      AUTHORIZED_KEYS: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      CEPH_NETWORK: 127.0.0.1/24
      MON_IP: 127.0.0.1
    net: host
    volumes: 
      - "{{ code_dir }}/ceph:/ceph"
      - "{{ code_dir }}/ceph-scripts:/ceph-scripts"
      - "/etc/ceph:/etc/ceph"
      - "/var/lib/ceph:/var/lib/ceph"
    privileged: yes
    state: restarted
    command: ceph-fuse /mnt/ -d
