# Author: Michael Sevilla
# Build Ceph in a container

- name: pull container for building ceph
  ignore_errors: True
  no_log: True
  docker: 
    image: ivotron/cephdev-build
    state: present

- name: build ceph
  docker:
    image: ivotron/cephdev-build
    name: cephdev-build
    env:
      BUILD_THREADS: "{{ threads }}"
      CEPH_PKGS: "{{ pkgs }}"
      GIT_URL: "{{ git_url }}"
      SHA1_OR_REF: "{{ commit }}"
      CXXFLAGS: "{{ cxxflags }}" 
      CFLAGS: "{{ cflags }}"
    volumes:
      - '{{ code_dir }}/ceph:/ceph'

- name: compiling; to see progress -> docker logs -f cephdev-build
  shell: docker wait cephdev-build
  register: result

- name: fail if docker build fails
  fail: msg="Ceph build failed; check your environment variables above"
  # stdout returns strings, not an int
  when: result.stdout.find("0") == -1

