# Author: Michael Sevilla
# Build ceph

- name: build ceph
  docker:
    image: ivotron/cephdev-build
    name: cephdev-build
    env:
      BUILD_THREADS: 32
      CEPH_PKGS: --with-lttng
    volumes:
      - '{{ code_dir }}/ceph:/ceph'

- name: wait for compile... (to see progress, ssh to node and run -> docker logs cephdev-build)
  shell: >
    docker wait cephdev-build
