---
- name: run the swift account daemon
  docker:
    image: "{{ swift_docker_username }}/{{ swift_docker_imagename }}"
    name: "{{ ansible_hostname }}-port{{ item }}-account"
    net: "host"
    state: "running"
    env: "IP={{ hostvars[inventory_hostname]['ansible_' + swift_account_docker_interface]['ipv4']['address'] }},PORT={{ item }},SWIFT_DAEMON=ACCOUNT,{{ swift_account_extra_envs }}"
    volumes: "/tmp/etc/swift/account{{ item }}/etc/swift:/etc/swift"
    detach: true
    tty: true
    privileged: true
  with_items: swift_account_docker_ports

- pause: minutes=1
- name: move configuration file to avoid re-starting this daemon
  command: docker exec {{ ansible_hostname }}-port{{ item }}-account mv /etc/swift/account-server.conf /root/account-server.conf
  with_items: swift_account_docker_ports
