# Author: Michael Sevilla
# Create a Tachyon node (with the source code)

- name: pull dependencies for running jxio
  ignore_errors: True
  no_log: True
  docker: 
    image: michaelsevilla/tachyondev
    state: present

- name: start the jxio server in a tachyon container
  docker:
    image: michaelsevilla/tachyondev
    name: "{{ container }}"
    state: restarted
    privileged: yes
    detach: yes
    tty: yes
    net: host
    volumes: 
      - "{{ code_dir }}/tachyon:/tachyon"
      - "{{ code_dir }}/JXIO:/JXIO"
    command: /JXIO/examples/runHelloWorld.sh server tcp {{ inventory_hostname }} 1234
