# Author: Michael Sevilla
# Start a parser node to interpret logs/metrics collected

- name: move some startup scripts over there
  copy: src=/infra/roles/ceph/parse/lttng/files/ dest={{ code_dir }}/

- name: make scripts executable
  command: chmod -R 750 {{ code_dir }}/scripts/

- name: pull dependencies for running parsing scripts
  ignore_errors: True
  no_log: True
  docker: 
    image: michaelsevilla/parser
    state: present

- name: start parser container
  docker:
    image: michaelsevilla/parser
    name: parser
    state: restarted
    volumes: 
      - "{{ code_dir }}/scripts:/scripts"
      - "{{ trace_dir }}/lttng:/lttng"
    command: /scripts/latency.py -o /lttng/latencies.out -d /lttng/ust/uid/0/64-bit/

- name: parsing scripts...
  shell: docker wait parser

- name: print out the results in {{ trace_dir }}/lttng/latencies.out
  changed_when: False
  command: cat {{ trace_dir }}/lttng/latencies.out
  register: result
- debug: var=result.stdout_lines
