# Author: Michael Sevilla
# Start a Ceph node with Mantle

- name: move some startup scripts over there
  copy: src=/infra/roles/mantle/deploy/files/ dest={{ code_dir }}/

- name: make scripts executable
  file: path="{{ code_dir }}/mantle-scripts/" mode=0750

- name: pull dependencies for running mantle
  ignore_errors: True
  no_log: True
  docker: 
    image: michaelsevilla/mantledev:master
    state: present

- name: start mantle container
  docker:
    image: michaelsevilla/mantledev:master
    name: "{{ container }}"
    state: restarted
    privileged: yes
    detach: yes
    tty: yes
    env:
      SSHD_PORT: "{{ sshd_port }}"
      AUTHORIZED_KEYS: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      CEPH_NETWORK: 127.0.0.1/24
      MON_IP: 127.0.0.1
    net: host
    volumes: 
      - "{{ code_dir }}/mantle/ceph:/ceph"
      - "{{ code_dir }}/mantle-scripts:/mantle-scripts"
      - "/tmp/etc/ceph:/etc/ceph"
      - "/tmp/ceph_data/$RANDOM:/var/lib/ceph"
      - "/dev:/dev"

- name:  give the container a second to come up
  pause: seconds=5

- name: check if the container came up properly
  fail: msg="The Mantle container is not running, check with [docker logs {{ container }}]."
  when: startup == "none"

- name: start ceph daemons
  command: docker exec mantle /mantle-scripts/{{ startup }}
