---
- name: run the swift object daemon
  shell: >
         docker run -it -d \
         --name "{{ ansible_hostname }}-port{{ item }}-object" \
         --net host \
         --privileged \
         -e "IP={{ ansible_host }}" \
         -e "PORT={{ item }}" \
         -e "SWIFT_DAEMON=OBJECT" \
         -v "/tmp/etc/swift/object{{ item }}/etc/swift:/etc/swift" \
         "{{ swift_docker_username }}/{{ swift_docker_imagename }}"
  with_items: swift_object_docker_ports
