# Author: Michael Sevilla
# Push the keys

- name: enable passwordless login
  authorized_key: user={{ ansible_ssh_user }}  key={{ lookup('file', '~/.ssh/id_rsa.pub') }}

- name: make directory for docker volumes
  file: path=/tmp/docker/ state=directory mode=0777

- name: make directory for components' src code
  file: path=/tmp/docker/src state=directory mode=0777

- name: make directory for components' deploy code
  file: path=/tmp/docker/deploy state=directory mode=0777
