# Author: Michael Sevilla
# Build jxio 

- name: pull dependencies for building jxio binaries
  ignore_errors: True
  no_log: True
  docker: 
    image: michaelsevilla/jxiodev-build
    state: present

- name: start jxio build container 
  docker:
    image: michaelsevilla/jxiodev-build
    name: "{{ container }}"
    state: restarted
    net: host
    env:
      SHA1_OR_REF: "{{ commit }}"
      GIT_URL: "{{ git_url }}"
    volumes:
      - "{{ code_dir }}/JXIO:/JXIO"

- name: compiling (run [docker logs -f jxio-build] on Builder for progress)
  shell: docker wait jxio-build
  register: result

- name: fail if docker build fails
  fail: msg="JXIO build failed; log into the Builder and run - docker logs jxio-build"
  when: result.stdout.find("0") == -1
