# Author: Michael Sevilla
# Start a Ceph node with Mantle

- name: move some startup scripts over there
  copy: src=/infra/roles/mantle/files/ dest={{ code_dir }}/

- name: make scripts executable
  command: chmod -R 750 {{ code_dir }}/mantle-scripts/

- name: pull dependencies for running mantle
  ignore_errors: True
  no_log: True
  docker: 
    image: michaelsevilla/mantledev
    state: present

- name: pull dependencies for mantle and start container 
  docker:
    image: michaelsevilla/mantledev
    name: mantle
    state: restarted
    privileged: yes
    detach: yes
    tty: yes
    env:
      SSHD_PORT: 2222
      AUTHORIZED_KEYS: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      CEPH_NETWORK: 127.0.0.1/24
      MON_IP: 127.0.0.1
    net: host
    volumes: 
      - "{{ code_dir }}/mantle/ceph:/ceph"
      - "{{ code_dir }}/mantle-scripts:/mantle-scripts"
      - "/etc/ceph:/etc/ceph"
      - "/var/lib/ceph:/var/lib/ceph"

- name: start ceph daemons
  command: docker exec mantle /mantle-scripts/{{ STARTUP }}
