# Author: Michael Sevilla
# Build Tachyon in a container

- name: check to see if user already checked out tachyon src
  command: ls -alh {{ code_dir }}/tachyon/.git
  register: result
  no_log: True
  ignore_errors: True
  changed_when: False

- name: fail if code does not exist
  fail: msg="Please put the Tachyon source code in {{ code_dir }}/tachyon/.git"
  when: result.rc != 0

- name: pull dependencies for building tachyon
  ignore_errors: True
  no_log: True
  docker: 
    image: michaelsevilla/tachyondev-build
    state: present

- name: build tachyon
  docker:
    image: michaelsevilla/tachyondev-build
    name: "{{ container }}"
    net: host
    state: started
    env: 
        SHA1_OR_REF: "{{ commit }}"
        JAR_ARGS: -Dfile=/JXIO/bin/jxio.jar -DgroupId=org.accelio.jxio -DartifactId=Msg -Dversion=v1.3-22-g01ef2ea -Dpackaging=jar -DskipTests 
    volumes:
        - "{{ code_dir }}/tachyon:/tachyon"
        - "{{ code_dir }}/JXIO:/JXIO"

- name: wait for compile (run [docker logs -f tachyon-build] on Builder for progress)
  shell: docker wait {{ container }}
  register: result

- name: fail if docker build fails
  fail: msg="Tachyon build failed; log into the Builder and run - docker logs {{ container }}..."
  # stdout returns strings, not an int
  when: result.stdout.find("0") == -1
