# Author: Michael Sevilla
# Get the source code and compile it in a tachyon container

- name: compile tachyon code using a container
  docker:
    image: michaelsevilla/tachyondev-build
    name: tachyondev-build
    env: 
        SHA1_OR_REF: remotes/origin/3par
    volumes: /tmp/docker/tachyon:/tachyon
    state: started

- name: wait for compile... (to see progress, ssh to node and run -> docker logs tachyondev-build)
  shell: > 
    docker wait tachyondev-build

