# Author: Michael Sevilla
# Build Tachyon in a container

- name: check to see if user already checked out tachyon src
  command: ls -alh {{ code_dir }}/tachyon/.git
  register: result
  no_log: True
  ignore_errors: True
  changed_when: False

- name: fail if code does not exist
  fail: msg="Please put the Tachyon source code in {{ code_dir }}/tachyon/.git"
  when: result.rc != 0

- name: build tachyon
  changed_when: False
  docker:
    image: michaelsevilla/tachyondev-build
    name: tachyondev-build
    env: 
        SHA1_OR_REF: remotes/origin/3par
        JAR_ARGS: -Dfile=/JXIO/bin/jxio.jar -DgroupId=org.accelio.jxio -DartifactId=Msg -Dversion=v1.3-22-g01ef2ea -Dpackaging=jar -DskipTests 
    volumes:
        - "{{ code_dir }}/tachyon:/tachyon"
        - "{{ code_dir }}/JXIO:/JXIO"
    state: started

- name: wait for compile... (to see progress, ssh to node and run [docker logs tachyondev-build])
  shell: > 
    docker wait tachyondev-build
  register: result

- name: fail if docker build fails
  fail: msg="Tachyon build failed; log into the Builder and run - docker logs tachyondev-build"
  # stdout returns strings, not an int
  when: result.stdout.find("0") == -1
