# Author: Michael Sevilla
# Start Tachyon

- name: create a tachyon environment variables file
  shell: cp {{ tmpdir }}/tachyon/conf/tachyon-env.sh.template {{ tmpdir }}/tachyon/conf/tachyon-env.sh

- name: set master address to the master
  lineinfile: dest={{ tmpdir }}/tachyon/conf/tachyon-env.sh 
              regexp="^export TACHYON_MASTER_ADDRESS=" 
              insertafter="^#export TACHYON_MASTER_ADDRESS=" 
              line="export TACHYON_MASTER_ADDRESS="{{ groups['TachyonMaster'][0] }}

- name: set worker addresses to the workers
  copy: content="{{ groups['TachyonWorkers'][0] }}\n" dest={{ tmpdir }}/tachyon/conf/workers

#- name: set journal folder as a shared undered folder in underfs
#  lineinfile: dest={{ tmpdir }}/tachyon/conf/tachyon-site.properties
#              line="tachyon.master.journal.folder=${tachyon.underfs.address}/tachyon/journal/"

