# Adapted from https://github.com/amplab/tachyon.git
# Author: Michael Sevilla

- hosts: all
  vars:
    tachyon: /opt/tachyon-0.7.1/
  tasks:
    - name: install the tachyon docker image
      docker: 
        name: 

- hosts: TachyonMaster*
  vars:
    tachyon: /opt/tachyon-0.7.1/
  tasks:
    - name: set master address to own hostname
      shell: sed -i "s/export TACHYON_MASTER_ADDRESS=.*/export TACHYON_MASTER_ADDRESS=$(hostname -A | cut -d' ' -f1)/g" {{ tachyon }}/conf/tachyon-env.sh

    - name: set journal folder as a shared undered folder in underfs
      shell: echo 'tachyon.master.journal.folder=${tachyon.underfs.address}/tachyon/journal/' >> {{ tachyon }}/conf/tachyon-site.properties

    - include: roles/tachyon/tasks/start_master.yml

- hosts: all
  vars:
    tachyon: /opt/tachyon-0.7.1/
  tasks:
    - include: roles/tachyon/tasks/start_worker.yml
