# Author: Michael Sevilla
# Build Ceph with Mantle in a container

- name: pull dependencies for building mantle
  ignore_errors: True
  no_log: True
  docker: 
    image: michaelsevilla/mantledev-build
    state: present

- name: build ceph
  no_log: True
  docker:
    image: michaelsevilla/mantledev-build
    name: mantledev-build
    env:
      BUILD_THREADS: "{{ threads }}"
      CEPH_PKGS: "{{ pkgs }}"
      GIT_URL: "{{ git_url }}"
      SHA1_OR_REF: "{{ commit }}"
    volumes:
      - '{{ code_dir }}/ceph:/ceph'

- name: compiling (run [docker logs mantledev-build] on Builder for progress)
  shell: docker wait mantledev-build
  register: result

- name: fail if docker build fails
  fail: msg="Ceph build failed; check your environment variables above"
  # stdout returns strings, not an int
  when: result.stdout.find("0") == -1

