# Author: Michael Sevilla
# Create a Ceph node

- name: pull/install a ceph container
  docker:
    image: ceph/demo
    name: ceph
    tty: yes
    env:
       CEPH_NETWORK: 127.0.0.1/24
       MON_IP: 127.0.0.1
    net: host
    volumes: 
        - /etc/ceph:/etc/ceph
        - /tmp/docker/usr/lib/rados-classes/:/usr/lib/rados-classes/
    privileged: yes
    state: started
