# Author: Michael Sevilla
# Start a Ceph node

- name: start ceph
  docker:
    image: ivotron/cephdev
    name: cephdev
    detach: yes
    tty: yes
    env:
      SSHD_PORT: 2222
      AUTHORIZED_KEYS: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      CEPH_NETWORK: 127.0.0.1/24
      MON_IP: 127.0.0.1
    net: host
    volumes: 
      - "{{ code_dir }}/ceph:/ceph"
      - "/etc/ceph:/etc/ceph"
      - "/var/lib/ceph:/var/lib/ceph"
    privileged: yes
    state: restarted
    command: standalone.sh

#- name: wait for the container to initialize
#  pause: seconds=1
#
#- name: add the ceph container to the ansible hosts
#  add_host: <
#            name={{ inventory_hostname }}:2222
#            ansible_ssh_user=root
#            group=ceph_mon_containers
