# Author: Michael Sevilla
# Start a Ceph node

- name: move some startup scripts over there
  copy: src=/infra/roles/ceph/files/ dest={{ code_dir}}/

- name: make scripts executable
  command: chmod -R 750 {{ code_dir}}/ceph-scripts/

- name: start ceph container 
  docker:
    image: ivotron/cephdev
    name: cephdev
    detach: yes
    tty: yes
    env:
      SSHD_PORT: 2222
      AUTHORIZED_KEYS: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      CEPH_NETWORK: 127.0.0.1/24
      MON_IP: 127.0.0.1
    net: host
    volumes: 
      - "{{ code_dir }}/ceph:/ceph"
      - "{{ code_dir }}/ceph-scripts:/ceph-scripts"
      - "/etc/ceph:/etc/ceph"
      - "/var/lib/ceph:/var/lib/ceph"
    privileged: yes
    state: restarted


