# Author: Michael Sevilla
# Start a Ceph node

- name: start ceph container 
  docker:
    image: ivotron/cephdev
    name: cephdev
    detach: yes
    tty: yes
    env:
      SSHD_PORT: 2222
      AUTHORIZED_KEYS: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      CEPH_NETWORK: 127.0.0.1/24
      MON_IP: 127.0.0.1
    net: host
    volumes: 
      - "{{ code_dir }}/ceph:/ceph"
      - "/etc/ceph:/etc/ceph"
      - "/var/lib/ceph:/var/lib/ceph"
    privileged: yes
    state: restarted

- name: start ceph in said container 
  command: docker exec cephdev /standalone.sh
