---

- name: figure out which configs the user has defined
  connection: local
  command: ls {{ playbook_dir }}/group_vars/hadoop_conf
  register: confs
  ignore_errors: True

- name: copy the user-defined configs to the remote note
  copy: src={{ playbook_dir }}/group_vars/hadoop_conf/{{ item }} dest=/etc/hadoop/{{ item }}
  with_items: confs.stdout_lines

- name: set config and keys paths
  command: ls /etc/hadoop
  register: ls

- name: push hadoop files to the ansible server
  fetch:
    src: "/etc/hadoop/{{ item }}"
    dest: "{{ fetch_directory }}/docker_hadoop_files/{{ item }}"
    flat: yes
  with_items: ls.stdout_lines
