---
- name: check if a cluster is already running
  shell: "docker ps | grep -sq '{{ hadoop_docker_username }}/{{ hadoop_docker_imagename }}'"
  register: hadoop_health
  changed_when: false
  failed_when: false

- include: checks.yml
  when: hadoop_health.rc != 0

- include: selinux.yml
  when: ansible_os_family == 'RedHat'

- include: start_docker_config.yml
- include: copy_configs.yml
