---
- name: generate hadoop configs
  shell: >
    docker run \
      --name hadoop-config \
      --net host \
      -e "HADOOP_DAEMON=CONFIG" \
      -v "/etc/hadoop:/etc/hadoop" \
      "{{ hadoop_docker_username }}/{{ hadoop_docker_imagename }}"

- name: wait for the container to populate the configs
  shell: docker wait hadoop-config
