---
- name: generate hadoop configs 
  docker:
    image: "{{ hadoop_docker_username }}/{{ hadoop_docker_imagename }}"
    name: "hadoop-config"
    net: "host"
    state: "running"
    env: "HADOOP_DAEMON=CONFIG"
    volumes: "/etc/hadoop:/etc/hadoop"

- name: wait for the container to populate the configs
  shell: docker wait hadoop-config
