# Author: Michael Sevilla
# Get the source code and compile it in a tachyon container

- name: clone compile tachyon code using a container
  docker:
    image: michaelsevilla/tachyondev-build
    name: tachyondev-build
    detach: false
    net: host
    env: 
        SHA1_OR_REF: origin/branch-0.7
    volumes: /tmp/docker/tachyon:/tachyon
    privileged: yes
    state: started

- name: wait for compile... (to see progress, ssh to node and run -> docker logs tachyondev-build)
  shell: > 
    docker wait tachyondev-build

