# Author: Michael Sevilla
# Package up the source code in preparation for network transfer

- name: delete archived tachyon code
  file: path={{ tmpdir }}/tachyon.tar.gz state=absent

- name: package up the tachyon code
  shell: tar czvf {{ tmpdir }}/tachyon.tar.gz {{ tmpdir }}/tachyon

