---
- include: selinux.yml
  when: ansible_os_family == 'RedHat'

- name: start collectl
  shell: >
    docker run \
      --name "collectl" \
      --net host \
      -e "ARGS={{ args }} --export graphite,{{ groups.graphite[0] }}" \
      "{{ collectl_docker_username }}/{{ collectl_docker_imagename }}"
