---
- include: selinux.yml
  when: ansible_os_family == 'RedHat'

- name: start collectl
  shell: >
    docker run -d \
      --name "{{ collectl_container_name }}" \
      --net host \
      -e "ARGS={{ collectl_args }} --export graphite,{{ groups.graphite[0] }}" \
      "{{ collectl_docker_username }}/{{ collectl_docker_imagename }}"
