---
- name: run the hadoop datanode docker image
  shell: >
    docker run -dt \
      --name "hadoop-datanode" \
      --net host \
      -e "HADOOP_DAEMON=DATANODE" \
      -e "HADOOP_CLASSPATH=/usr/local/hadoop/share/hadoop/tools/lib/*" \
      -e "YARN_CLASSPATH=/usr/local/hadoop/share/hadoop/tools/lib/*" \
      -v "/etc/hadoop:/etc/hadoop" \
      "{{ hadoop_docker_username }}/{{ hadoop_docker_imagename }}"
