# Author: Michael Sevilla
# Bring up Ceph with the origianl Mantle on a single node

- name: cleanup old experiments
  hosts: all
  roles:
    - role:       cleanup
      containers: "mantle client"

- hosts: localhost
  roles: 
    - role:     mantle/build
      code_dir: "/tmp/docker/src/mantle"
      git_url:  "https://github.com/michaelsevilla/ceph.git"
      commit:   "remotes/origin/wip-mantle-dev"
      pkgs:     "--with-mantle"
      threads:  "64"

- name:  start Mantle and set the balancer to greedy-spill
  hosts: Workers
  roles:
    - role:     mantle/deploy
      startup: "standalone.sh"
  tasks:
    - name:    set the balancer to greedy-spill
      command: docker exec mantle /mantle-scripts/greedy-spill.sh

- name:  run benchmark
  hosts: localhost
  roles: 
    - role:      ceph/deploy
      startup:   "none"
      container: client
      sshd_port: 2223
  tasks:
    - name:     mount the file system
      command:  docker exec -d client ceph-fuse /mnt/ -d
    - name:     start the mdtest benchmark
      command:  docker exec client mdtest -F -C -n 10000 -d /mnt/testdir
      register: result
    - debug:    var=result.stdout_lines
