---
- name: check if a cluster is already running
  shell: "docker ps | grep -sq 'swift/daemon'"
  register: swift_health
  changed_when: false
  failed_when: false

- include: checks.yml
  when: swift_health.rc != 0

- include: pre_requisite.yml
  when: install_docker
- include: selinux.yml
  when: ansible_os_family == 'RedHat'

- include: start_docker_config.yml
- include: copy_configs.yml
