---
- name: run the gassyfs docker image
  docker:
    image: "{{ gassyfs_docker_username }}/{{ gassyfs_docker_imagename }}"
    name: "{{ container_name_worker }}"
    net: "host"
    state: "running"
    env: 
      DAEMON: "WORKER"
      SRC_DIR: "{{ src_directory }}"
      SSHD_PORT: "{{ worker_sshd_port }}"
      AUTHORIZED_KEYS: "{{ authkey }}"
      INFINIBAND: "{{ infiniband }}"
      GASNET_COMPILE_ARGS: "{{ gasnet_compile_args }}"
      GASNET_MASTERIP: "{{ ansible_host }}"
      NO_UNIX_SOCKETS: 1 
      GIT_URL: "{{ git_url }}"
      GIT_COMMIT: "{{ git_commit }}"
    volumes:
      - "{{ src_directory }}/worker:{{ src_directory }}"
      - "/dev/shm:/dev/shm"
      - "/run/shm:/run/shm"
      - "{{ home_directory }}:/home"
    privileged: True
