---
- name: run the gassyfs docker image
  shell:
    docker run --privileged -d \
      --name "{{ container_name_worker }}" \
      --net host \
      -e "DAEMON=WORKER" \
      -e "SRC_DIR={{ src_directory }}" \
      -e "SSHD_PORT={{ worker_sshd_port }}" \
      -e "AUTHORIZED_KEYS={{ authkey }}" \
      -e "INFINIBAND={{ infiniband }}" \
      -e "GASNET_COMPILE_ARGS={{ gasnet_compile_args }}" \
      -e "GASNET_MASTERIP={{ ansible_host }}" \
      -e "NO_UNIX_SOCKETS=1" \
      -e "GIT_URL={{ git_url }}" \
      -e "GIT_COMMIT={{ git_commit }}" \
      -v "{{ src_directory }}/worker:{{ src_directory }}" \
      -v "/dev/shm:/dev/shm" \
      -v "/run/shm:/run/shm" \
      -v "{{ home_directory }}:/home" \
      "{{ gassyfs_docker_username }}/{{ gassyfs_docker_imagename }}"
