---
- name: run the gassyfs docker image
  docker:
    image: "{{ gassyfs_docker_username }}/{{ gassyfs_docker_imagename }}"
    name: "{{ container_name_worker }}"
    net: "host"
    state: "running"
    env: "DAEMON=WORKER,SRC_DIR={{ src_directory }},SSHD_PORT={{ worker_sshd_port }},AUTHORIZED_KEYS=\"{{ authkey }}\""
    volumes: "{{ src_directory }}:{{ src_directory }},/dev/shm:/dev/shm,/run/shm:/run/shm"
    privileged: True
