---
- name: run the swift container daemon
  shell: >
         docker run -it -d \
         --name "{{ ansible_hostname }}-port{{ item }}-container" \
         --net host \
         --privileged \
         -e "IP={{ ansible_host }}" \
         -e "PORT={{ item }}" \
         -e "SWIFT_DAEMON=CONTAINER" \
         -v "/tmp/etc/swift/container{{ item }}/etc/swift:/etc/swift" \
         "{{ swift_docker_username }}/{{ swift_docker_imagename }}"
  with_items: swift_container_docker_ports
