---
#- include: checks.yml
- include: pre_requisite.yml
  when: install_docker
- include: selinux.yml
  when: ansible_os_family == 'RedHat'

#- include: fetch_configs.yml
- include: start_docker_nodemanager.yml
