---
- name: run the hadoop nodemanager docker image
  docker:
    image: "{{ hadoop_docker_username }}/{{ hadoop_docker_imagename }}"
    name: "{{ ansible_hostname }}-nodemanager"
    net: "host"
    state: "running"
    env: "HADOOP_DAEMON=NODEMANAGER,{{ hadoop_nodemanager_extra_envs }}"
    volumes: "/etc/hadoop:/etc/hadoop,{{ deploy_dir }}/{{ code_dir }}/hadoop:/hadoop"
    detach: true
    tty: true
