# Author: Michael Sevilla
# Cleanup containers on all nodes

- name: delete data
  file: path="/tmp/etc" state=absent
- file: path="/tmp/ceph_data/" state=absent
- file: path="/usr/local/share/ceph/rados-classes/" state=absent

- name: delete user defined directories 
  when: delete is defined
  file: path="{{ delete }}/" state=absent
  ignore_errors: True

- name: stop containers -> {{ containers }}
  when: containers is defined
  with_items: "{{ containers }}"
  shell: docker stop {{ item }}
  ignore_errors: True
  no_log: True

- name: remove containers -> {{ containers }}
  when: containers is defined
  with_items: "{{ containers }}"
  shell: docker rm {{ item }}
  ignore_errors: True
  no_log: True
