---
- include: pre_requisite.yml
  when: install_docker
- include: selinux.yml
  when: ansible_os_family == 'RedHat'

- name: start graphite
  docker:
    image: "{{ graphite_docker_username }}/{{ graphite_docker_imagename }}"
    name: "graphite"
    net: "host"
    state: "running"
    volumes: "/tmp/graphite:/tmp/graphite"
    env:
      APACHE_PORT: "8081"
      WEBUI_PORT: "8080"
