# Author: Michael Sevilla
# Build lua-rados bindings

- name: pull container for building lua-rados bindings
  ignore_errors: True
  no_log: True
  docker: 
    image: michaelsevilla/lua-rados-build
    state: present

- name: build lua-rados bindings
  no_log: True
  docker:
    image: michaelsevilla/lua-rados-build
    name: "{{ container }}"
    state: restarted
    detach: yes
    tty: yes
    net: host
    env:
      SSHD_PORT: "{{ sshd_port }}"
      AUTHORIZED_KEYS: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      CEPH_NETWORK: 127.0.0.1/24
      MON_IP: 127.0.0.1
    volumes: 
      - "{{ code_dir }}/ceph:/ceph"
      - "{{ code_dir }}/ceph-scripts:/ceph-scripts"
      - "{{ trace_dir }}/lttng:/lttng"
      - "/etc/ceph:/etc/ceph"
      - "/var/lib/ceph:/var/lib/ceph"
      - "/dev:/dev"

